spring:
datasource:
  url:jdbc:h2:file:./stddb
  driverClassName:org.h2.Driver
  username:Abhi
  password:1289
jpa:
  database-platform:org.hibernate.dialect.H2Dialect
camunda.bpm.admin-user:
  id:aa
  password:aa
spring.h2.console:
  enabled:true
  path:/h2-console